################################################################################
# Services for OpenText CSP
################################################################################


################################################################################
# OpenText Content Server - Frontend load balancer
# Exposed outside the kubernetes cluster as a Load Balancer
################################################################################
kind: Service
apiVersion: v1
metadata:
  name: otcs-frontend
spec:
  type: LoadBalancer
  # Below is required for Content Server to have the original client IP to
  # create login cookie
  externalTrafficPolicy: Local
  ports:
  - name: "80"
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: otcs-frontend
---

################################################################################
# OpenText Content Server - Primary Admin 
################################################################################
kind: Service
apiVersion: v1
metadata:
  name: otcs-admin-0
spec:
  ports:
  - name: "80"
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: "5858"
    protocol: TCP
    port: 5858
    targetPort: 5858
  - name: "5869"
    protocol: TCP
    port: 5869
    targetPort: 5869
  - name: "8500"
    protocol: TCP
    port: 8500
    targetPort: 8500
  - name: "8501"
    protocol: TCP
    port: 8501
    targetPort: 8501
  - name: "8502"
    protocol: TCP
    port: 8502
    targetPort: 8502
  - name: "8503"
    protocol: TCP
    port: 8503
    targetPort: 8503
  - name: "8504"
    protocol: TCP
    port: 8504
    targetPort: 8504
  - name: "8505"
    protocol: TCP
    port: 8505
    targetPort: 8505
  - name: "8506"
    protocol: TCP
    port: 8506
    targetPort: 8506
  - name: "8507"
    protocol: TCP
    port: 8507
    targetPort: 8507
  - name: "8508"
    protocol: TCP
    port: 8508
    targetPort: 8508
  - name: "8509"
    protocol: TCP
    port: 8509
    targetPort: 8509
  - name: "8510"
    protocol: TCP
    port: 8510
    targetPort: 8510
  - name: "8511"
    protocol: TCP
    port: 8511
    targetPort: 8511
  # Note: These ports represent memcached ports
  - name: "8512"
    protocol: TCP
    port: 8512
    targetPort: 8512
  - name: "8513"
    protocol: TCP
    port: 8513
    targetPort: 8513
  - name: "8514"
    protocol: TCP
    port: 8514
    targetPort: 8514
  selector:
    app: otcs-admin
---

################################################################################
# OpenText Archive Center
################################################################################
kind: Service
apiVersion: v1
metadata:
  name: otac-0
spec:
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: otac
---

################################################################################
# OpenText Directory Services (OTDS)
# Exposed outside the kubernetes cluster as a Load Balancer
################################################################################
kind: Service
apiVersion: v1
metadata:
  name: otds
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: otds
---

################################################################################
# Postgres DB for OpenText Archive Center
# Not exposed outside the kubernetes cluster. To do so, Uncomment LoadBalancer
# line below if this is needed
################################################################################
kind: Service
apiVersion: v1
metadata:
  name: otac-db
spec:
  #type: LoadBalancer
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: otac-db
---

################################################################################
# Postgres DB for OpenText Content Server
# Not exposed outside the kubernetes cluster. To do so, uncomment LoadBalancer 
# line below if this is needed
################################################################################
kind: Service
apiVersion: v1
metadata:
  name: otcs-db
spec:
  #type: LoadBalancer
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: otcs-db
---
